##########################################################################
# Standard Properties
org.gradle.jvmargs = -Xmx1G
org.gradle.warning.mode = all
##########################################################################
# Standard Fabric Dependencies
# Check these on https://fabricmc.net/develop
minecraft_version = 26.1.2
loader_version = 0.19.3
# Fabric API
fabric_version = 0.153.0+26.1.2
loom_version = 1.17-SNAPSHOT
java_version = 25
##########################################################################
# Mod Properties
mod_version = 4.0.0
maven_group = cc.dvitski
archives_base_name = direbats
mod_id = direbats
##########################################################################
# Publishing
major_version = 1.20.8
mod_name = Direbats
supported_versions = 1.20.8
release_type = release
github_repository = andantet/direbats
github_branch = latest
modrinth_id = epF1CjCx
curseforge_id = 407987
##########################################################################
# Kotlin Dependencies
systemProp.kotlin_version = 2.2.0
fabric_language_kotlin_version = 1.13.4+kotlin.2.2.0
##########################################################################
